### ISSUE TITLE
use material ui

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/generator-jhipster-react#1]
this seems like a very nice set of react components that we could use
http://www.material-ui.com/#/components/app-bar

@ykushch @Dhiviya-Bharathi

**Comment by ykushch** [comment]
@deepu105 I think of this http://elemental-ui.com/

**Comment by deepu105** [comment]
Does elemental ui support bootstrap themes? if yes then it might be good
choice if not i would go with material for below reasons

Its more mature and stable
13000+ stars vs 2000+ stars (that's a huge difference)
more components (has all components we would need without any additional
dependency)
better looking
easy to change theme colors

Thanks & Regards,
Deepu

**Comment by ykushch** [comment]
Yes, I've seen that. But it seems that there are issues with IE 10, 11 (that's quite a lot). https://github.com/callemall/material-ui/issues/468

**Comment by deepu105** [comment]
I checked in IE11 and Edge, In edge everything works perfectly fine, In IE all works except autocompelte (which we dont need actually) so thats good.

I wouldn't care about IE8/9/10 even MS stopped supporting them so no point worrying and holding back, if we are following Jhipster like front end then we would only use simpler features which seems to work well. So I would definitely prefer material ui

**Comment by ykushch** [comment]
Yep, that's right. They've dropped major versions. If it is not the case for us then sure - let's try out material-ui.

**Comment by deepu105** [comment]
Ok ill put up a template skeleton today. Im planning to go with gulp and
browserify coz the backend generated with Jhipster has gulp hooks from
maven gradle that will work for this.

If we go with webpack we dont get the hooks and stuff. What do you think is
that ok?

**Comment by deepu105** [comment]
I have added a client side app skeleton, see if its ok

**Comment by ykushch** [comment]
I'm looking into webpack right now. It seems that in react community it is more popular. Hot module replacement is great. Take a look at this [article](https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.x0lwkvh9o).

**Comment by deepu105** [comment]
ya i saw that, but with jhipter gulp is hooked into the maven/gradle
process. if we use webpack the build flow will be broken. if you have a
solution for that then im ok with webpack

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
closing since we are using material-ui
