### ISSUE TITLE
Add unit tests and e2e for generated code

### ISSUE THREAD

**Issue by sendilkumarn** [hipster-labs/generator-jhipster-react#15]
Consider adding [Jest](https://facebook.github.io/jest/) for testing

**Comment by deepu105** [comment]
Yes we need to add testing. But again I'm not a fan of these Rip offs produced by Facebook just for the sake of it. Its actually a Karma clone. We should rather try to stick to Karma for unit tests and for e2e we could try to reuse the protractor tests if possible but if that doesnt work out well we can use something like [Nightwatch](http://nightwatchjs.org/)
I would want to keep technologies as close as possible between Angular and React versions if possible. using something like Jest would make it hard for us to maintain these once we move this into the main generator. But ofcourse if you think that the value provided by Jest outweighs burden of maintenance compared to Karma then yes we can do it.
