### ISSUE TITLE
Migrate to Webpack

### ISSUE THREAD

**Issue by ykushch** [hipster-labs/generator-jhipster-react#3]
Consider using [webpack](https://webpack.github.io) instead of [browserify](http://browserify.org/) as [webpack](https://webpack.github.io) is more popular in react community.

**Comment by deepu105** [comment]
Ok then you can chamge to webpack. Lets figure out how to get it hooked to gradle or maven build later. The only reason i used gulp was becoz jhipster backend already hooks gulp build and gulp test into the gradle/maven lifcycle.

So if you do a gradle/mvn prod build ut will trigger your gulp build and gulp test as well

**Comment by ykushch** [comment]
Sure. Just want to try it out if it will work for us.

**Comment by deepu105** [comment]
you can refer the webpack example in material ui I guess, i took gulp code
from there

Thanks & Regards,
Deepu

**Comment by ykushch** [comment]
seems that I have some progress with webpack integration. Thank you for example with material-ui :)

**Comment by deepu105** [comment]
They had a nice example

**Comment by deepu105** [comment]
@ykushch did you make any progress? You can commit to master if you want I have given you write access

Let me know if you need any help

**Comment by ykushch** [comment]
Yes, there is some. Had a lot of work on this hot period. Will contribute soon.

**Comment by deepu105** [comment]
Sure, ill stay tuned

**Comment by ykushch** [comment]
I've uploaded first version of dev configuration. Seems that it works but in order to make it work properly I had to use [proxy mode in webpack](https://webpack.github.io/docs/webpack-dev-server.html).

**Comment by deepu105** [comment]
Im not familiar with webpack so Ill trust your judgement

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
can you close this if its done?

**Comment by ykushch** [comment]
Yes, let's close it for now
