### ISSUE TITLE
Issue with svg-image in README.md

### ISSUE THREAD

**Issue by ykushch** [hipster-labs/generator-jhipster-react#6]
It seems that github has disabled svg in readme. According to this [question](http://stackoverflow.com/a/16462143/2928710) on StackOverFlow we should pick it up from different source.

**Comment by deepu105** [comment]
Ok may be we can put up a PNG version

Thanks & Regards,
Deepu

**Comment by ykushch** [comment]
Yep, I think so too because svg needs to be pulled from gh-pages. Will convert svg to png and upload then.

**Comment by ykushch** [comment]
I've added png version of logo. Had to include it in readme as `<img></img>` tag in order to have an ability to use dimensions.

**Comment by deepu105** [comment]
ok
