### ISSUE TITLE
create settings and auth modules

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/generator-jhipster-react#8]

**Comment by abhayc77** [comment]
Is there a reference code/doc on the current JHipster I can look at  to understand this better?

**Comment by deepu105** [comment]
you could start by looking at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request for setup.

Once done then you need to generate an app using this generator and see how you can create pages similar to the ones generated by Jhipster using react instead of angular. we are planning to use http://www.material-ui.com/ instead of bootstrap so take a look at that as well.
