### ISSUE TITLE
create admin modules

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/generator-jhipster-react#9]

**Comment by nicholas-b-carter** [comment]
What is the approach that has been decided if any? Is this a direct port? If you have anymore information I would love to take a stab at it.

**Comment by deepu105** [comment]
Yes its a direct port. @sendilkumarn has been working on few pages but user management, audit etc are still not done so if you wanna help you are very welcome

**Comment by deepu105** [comment]
Here are the admin module located https://github.com/hipster-labs/generator-jhipster-react/tree/master/generators/client/templates/src/main/webapp/app/modules/administration

**Comment by nicholas-b-carter** [comment]
@deepu105, awesome just saw you responded. I'll check it out tonight and see how far I can get with it. Thanks!
